# Generated by Django 6.0.4 on 2026-04-15 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Tecnico', 'Tecnico'), ('Juridico', 'Juridico'), ('Atendente', 'Atendente'), ('Gestor', 'Gestor'), ('Auditor', 'Auditor')], default='Atendente', max_length=30)),
                ('superusuario', models.BooleanField(default=False)),
                ('admin_municipio', models.BooleanField(default=False)),
                ('profissional_interno', models.BooleanField(default=True)),
                ('usuario_externo', models.BooleanField(default=False)),
                ('visualizar', models.BooleanField(default=True)),
                ('editor', models.BooleanField(default=False)),
                ('comentar', models.BooleanField(default=True)),
                ('aprovar', models.BooleanField(default=False)),
                ('assinar', models.BooleanField(default=False)),
                ('exportar', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de acesso',
                'verbose_name_plural': 'Perfis de acesso',
            },
        ),
    ]
